German translation
pkp/browseBySection pull request #10
Opened 2018-09-04 12:25 UTC by st-schulte

I did a German translation for the plugin. Perhaps there is interest to transfer this into the main project.

2018-09-04 19:34 UTC, mtub requested changes
Thanks, Stefan. I have made a few comments to have this translation in sync with the rest of OJS, mostly having gender-neutral terms and replacing "publiziert" with "veröffentlicht". Could you update your pull request? (If you don't have the time I can do an update later…)

Danke!

2018-09-04 19:34 UTC, mtub commented on locale/de_DE/locale.xml
> +  * Localization strings for the de_DE (Deutsch) locale.
Deutsch -> Deutsch (Deutschland)

2018-09-04 19:34 UTC, mtub commented on locale/de_DE/locale.xml
> +	<message key="plugins.generic.browseBySection.description">Erlaubt Besuchern die Zeitschrift nach Rubriken durchzublättern.</message>
Erlaubt Besucher/innen, die Zeitschrift …

2018-09-04 19:34 UTC, mtub commented on locale/de_DE/locale.xml
> +	<message key="plugins.generic.browseBySection.emptySection">In dieser Rubrik wurde bislang kein Beitrag publiziert.</message>
… Beitrag veröffentlicht.

2018-09-04 19:34 UTC, mtub commented on locale/de_DE/locale.xml
> +	<message key="plugins.generic.browseBySection.enableBrowsing">Ermöglicht den Zugriff auf das Archiv mit allen publizierten Artikel einer Rubrik.</message>
allen veröffentlichten Artikeln

2018-09-04 19:34 UTC, mtub commented on locale/de_DE/locale.xml
> +	<message key="plugins.generic.browseBySection.browseByPathDescription">Passe den URL-Pfad an, über den Besucher auf das Archiv der Rubrik zugreifen können. Der Pfad darf nur Buchstaben, Zahlen und B
Besucher/innen

2018-09-04 19:34 UTC, mtub commented on locale/de_DE/locale.xml
> +	<message key="plugins.generic.browseBySection.navMenuItem.description">Link zu dem Archiv der publizierten Beiträge in dieser Rubrik.</message>
veröffentlichten Beiträge

2018-09-04 20:43 UTC, st-schulte commented
Thanks for your review, Marco. I have changed the translations accordingly.

2018-09-05 05:30 UTC, mtub commented on locale/de_DE/locale.xml
> +	<message key="plugins.generic.browseBySection.description">Erlaubt Besucher/innen die Zeitschrift nach Rubriken durchzublättern.</message>
There's a comma missing… mind sending a quick update? -> "Erlaubt Besucher/innen, die Zeitschrift…"

2018-09-05 05:52 UTC, st-schulte commented
Done!

2018-09-05 05:53 UTC, mtub commented
Thanks, Stefan. @NateWr, please go ahead and merge :+1:

2018-09-05 08:42 UTC, merged

2018-09-05 08:43 UTC, NateWr commented
:+1: Thanks to both of you!